#############################################################################
# Makefile for building: monitor
# Generated by qmake (2.01a) (Qt 4.8.6) on: mié mar 25 10:45:52 2015
# Project:  pvs.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile pvs.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = 
CFLAGS        = -m64 -pipe -O2 -Wall -W $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/opt/pvb/pvserver -I/opt/pvb/rllib/lib -I/usr/include/mysql
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)   /usr/lib/libpvsmt.so -lpthread /usr/lib/librllib.so -lmysqlclient 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ../lib/pugixml-1.5/src/pugixml.cpp \
		config.cpp \
		capture.cpp \
		database.cpp \
		main.cpp \
		mask1.cpp 
OBJECTS       = pugixml.o \
		config.o \
		capture.o \
		database.o \
		main.o \
		mask1.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		pvs.pro
QMAKE_TARGET  = monitor
DESTDIR       = 
TARGET        = monitor

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: pvs.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile pvs.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -o Makefile pvs.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/monitor1.0.0 || $(MKDIR) .tmp/monitor1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/monitor1.0.0/ && (cd `dirname .tmp/monitor1.0.0` && $(TAR) monitor1.0.0.tar monitor1.0.0 && $(COMPRESS) monitor1.0.0.tar) && $(MOVE) `dirname .tmp/monitor1.0.0`/monitor1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/monitor1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

pugixml.o: ../lib/pugixml-1.5/src/pugixml.cpp ../lib/pugixml-1.5/src/pugixml.hpp \
		../lib/pugixml-1.5/src/pugiconfig.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pugixml.o ../lib/pugixml-1.5/src/pugixml.cpp

config.o: config.cpp config.h \
		../lib/pugixml-1.5/src/pugixml.hpp \
		../lib/pugixml-1.5/src/pugiconfig.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o config.o config.cpp

capture.o: capture.cpp capture.h \
		../lib/pugixml-1.5/src/pugixml.hpp \
		../lib/pugixml-1.5/src/pugiconfig.hpp \
		config.h \
		database.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o capture.o capture.cpp

database.o: database.cpp database.h \
		config.h \
		../lib/pugixml-1.5/src/pugixml.hpp \
		../lib/pugixml-1.5/src/pugiconfig.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o database.o database.cpp

main.o: main.cpp pvapp.h \
		config.h \
		../lib/pugixml-1.5/src/pugixml.hpp \
		../lib/pugixml-1.5/src/pugiconfig.hpp \
		capture.h \
		database.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mask1.o: mask1.cpp pvapp.h \
		config.h \
		../lib/pugixml-1.5/src/pugixml.hpp \
		../lib/pugixml-1.5/src/pugiconfig.hpp \
		capture.h \
		database.h \
		mask1_slots.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mask1.o mask1.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

